### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Neney22** [karim0sec/tiktokdl#1]
hi, I keep getting this error when trying to download in bulk:

/Users/user/tiktokdl/node_modules/node-fetch/lib/index.js:273
				return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
				                           ^
FetchError: invalid json response body at https://api19-core-useast5.us.tiktokv.com/aweme/v1/feed/?aweme_id=7049220737701416238&version_code=262&app_name=musical_ly&channel=App&device_id=null&os_version=14.4.2&device_platform=iphone&device_type=iPhone9 reason: Unexpected token H in JSON at position 0
    at /Users/user/tiktokdl/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getVideoNoWM (/Users/user/tiktokdl/index.js:110:17)
    at async /Users/user/tiktokdl/index.js:250:89 {
  type: 'invalid-json'
}

Node.js v18.12.1

**Comment by karim0sec** [comment]
not sure seems internet problem delete node_module folder and npm i again 
if still getting same error delete package-lock.js + node_module and npm i again

**Comment by Neney22** [comment]
My internet is stable and speed at around 800Mbps, I tried both but it still doesn't find videos now:




? Choose a option Mass Download (Username)
? Choose a option Without Watermark
? Enter the username with @ (e.g. @username) :  karim0sec
[*] Getting list video from: karim0sec
[*] 0 video found
[X] No more video found
[*] Total video found: 0
[!] Error: No video found

**Comment by karim0sec** [comment]
![image](https://user-images.githubusercontent.com/92269255/200465288-3eec9dbf-caed-489b-aa24-7e7217eb9187.png)
just now with default package-lock.json i think tiktok blocked your ip address restart your router

**Comment by karim0sec** [comment]
i will update the project to parse json locally maybe there an error i couldn't detect

**Comment by karim0sec** [comment]
can you try now after update?

**Comment by Neney22** [comment]
THANKS FOR the update, so after the update, It was able to fetch the numbers of videos but after a while it gives me the following errors:


, [*] 1476 video found
[X] No more video found
[*] Total video found: 1476
[!] Found 1476 video
Error: SyntaxError: Unexpected token H in JSON at position 0
    at JSON.parse (<anonymous>)
    at getVideoNoWM (/Users/user/tiktokdl/index.js:112:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/user/tiktokdl/index.js:260:89
Response body: Header overflow
/Users/user/tiktokdl/index.js:117
                    return ReE(response, err.message, 500)
                    ^

ReferenceError: ReE is not defined
    at getVideoNoWM (/Users/user/tiktokdl/index.js:117:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/user/tiktokdl/index.js:260:89

Node.js v18.12.1

**Comment by karim0sec** [comment]
make sure that url have no spaces

**Comment by Neney22** [comment]
I am only trying to download a profile not URL, your program asks for the @

**Comment by karim0sec** [comment]
![image](https://user-images.githubusercontent.com/92269255/200482220-40c916a2-b3ba-495f-9553-65599b2d4fb9.png)
another proof that video you trying to download in single mode works fine so yeah url profile or @ both is same

**Comment by Neney22** [comment]
Error: SyntaxError: Unexpected token H in JSON at position 0
at JSON.parse () 

goes after find the videos

**Comment by Neney22** [comment]
if it works by single download, then it must be an issue with bulk? or is there a limit?

**Comment by karim0sec** [comment]
try last update please i wanna make sure if your ip blocked or an error accrue, nope bulk functionality works fine as long as it give you numbers of videos

**Comment by karim0sec** [comment]
oh i am using node v16.17.1 i'll update to see

**Comment by Neney22** [comment]
Yup, I just tried it with VPN & doesn't gives me the number of videos, without VPN it gives me the number of videos and then the same error as previous message sent. So maybe is either the version of node or my IP is blocked I guess. I noticed that before trying this project I used Bulk-Tiktoks-Downloader & it downloaded 200 videos and then it gave an error

**Comment by karim0sec** [comment]
![image](https://user-images.githubusercontent.com/92269255/200485491-b1020ad4-cf56-4962-a810-b5ce05b28716.png)
with latest node so yeah ip is blocked, i will slow it a bit in coming update so it can not be detected like huge traffic all in once

**Comment by Neney22** [comment]
damn sucks, and sounds like a good idea and it would also be cool if you added something to avoid downloading the same videos in case you lose connection or your ip gets blocked you get to continue downloading the bulk videos instead of redownloading all of them. Just giving you an idea :) I will try to restart router to see if I can get a new ip. Anyways awesome project man, it can save a lot of time for me if I get to fix my ip

**Comment by karim0sec** [comment]
yeah i will later, if you get an new error i'd be grateful to report

**Comment by Neney22** [comment]
**So after trying the latest update with Mass this is the error getting:**

[!] Found 309 video
Error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getVideoNoWM (/Users/user/tiktokdl/index.js:112:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/user/tiktokdl/index.js:258:89
Response body: 
/Users/user/tiktokdl/index.js:119
    const urlMedia = res.aweme_list[0].video.play_addr.url_list[0]
                         ^

TypeError: Cannot read properties of undefined (reading 'aweme_list')
    at getVideoNoWM (/Users/user/tiktokdl/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/user/tiktokdl/index.js:258:89

Node.js v18.12.1


**BUT with Single URL it downloads Successfully, this is same IP and same Terminal after running the Bulk command:**


? Choose a option Single Download (URL)
? Choose a option Without Watermark
? Enter the URL :  https://www.tiktok.com/@vava_us/video/7103395354451774762?is_
copy_url=1&is_from_webapp=v1
[!] Found 1 video
[+] Downloading 7103395354451774762.mp4
[+] Downloaded successfully


**I think the main issue is happening with the first Mass command**
